# Generated by Django 5.0.1 on 2024-02-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_picture/default_photo_picture.jpg",
                upload_to="profile_picture",
            ),
        ),
    ]
