# Generated by Django 5.0.1 on 2024-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_profile_voivodeship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="voivodeship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lower_silesia", "Lower Silesian"),
                    ("kuyavia-pomerania", "Kuyavian-Pomeranian"),
                    ("lublin", "Lublin"),
                    ("lubusz", "Lubusz"),
                    ("lodz", "Lodz"),
                    ("lesser_poland", "Lesser Poland"),
                    ("masovia", "Masovian"),
                    ("opole", "Opole"),
                    ("subcarpatia", "Subcarpathian"),
                    ("podlasie", "Podlasie"),
                    ("pomerania", "Pomeranian"),
                    ("silesia", "Silesian"),
                    ("swietokrzyskie", "Swietokrzyskie"),
                    ("warmia-masuria", "Warmian-Masurian"),
                    ("greater_poland", "Greater Poland"),
                    ("west_pomerania", "West Pomeranian"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
