# Generated by Django 5.0.1 on 2024-03-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_picture"),
        ),
    ]
