# Generated by Django 5.0.1 on 2024-03-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuser",
            name="is_set",
            field=models.BooleanField(
                default=False,
                help_text="This field is true when all of the fields are filled up.",
            ),
        ),
    ]
