# Generated by Django 5.0.1 on 2024-03-11 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_aboutuser_is_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diary",
            options={"ordering": ("-created",)},
        ),
    ]
