# Generated by Django 5.0.1 on 2024-03-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0011_alter_diary_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="expire_of_tier",
            field=models.DateField(
                blank=True,
                help_text="When this field is empty, it means that the curren type of user account is BASIC. Otherwise, it indicates the expiration of the current profile type.",
                null=True,
            ),
        ),
    ]
