# Generated by Django 5.0.1 on 2024-03-14 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0013_profile_female_visitor_profile_male_visitor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="best_friends",
            field=models.ManyToManyField(
                blank=True, related_name="best_friends", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
