# Generated by Django 5.0.1 on 2024-03-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_remove_friendrequest_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="emotion",
            field=models.TextField(
                choices=[
                    ("128522", "HAPPINESS"),
                    ("128546", "SADNESS"),
                    ("129336", "JEALOUSY"),
                    ("128554", "ENVY"),
                    ("128558", "EMPATHY"),
                    ("128533", "SYMPATHY"),
                    ("128557", "GRIEF"),
                    ("128519", "BLISS"),
                ],
                default="128522",
            ),
        ),
    ]
