# Generated by Django 5.0.1 on 2024-03-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0019_alter_profile_emotion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="emotion",
            field=models.TextField(
                choices=[
                    ("1F600", "Joy"),
                    ("1F601", "Happiness"),
                    ("1F60E", "Pride"),
                    ("1F63B", "Love"),
                    ("1F60D", "Fall In Love"),
                    ("1F62D", "Cry"),
                    ("1F631", "Screaming"),
                    ("1F634", "Sleeping"),
                ],
                default="1F601",
            ),
        ),
    ]
