# Generated by Django 5.0.1 on 2024-03-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0021_alter_profile_emotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="amt_of_galleries",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
