# Generated by Django 5.0.1 on 2024-03-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0022_profile_amt_of_galleries"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="size_of_pictures",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
