# Generated by Django 5.0.1 on 2024-04-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0023_profile_size_of_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="size_of_pictures",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Shows currently size of all pictures expressed by byte who belong to the particular user.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="type_of_profile",
            field=models.TextField(
                choices=[
                    ("B", "Basic"),
                    ("P", "Pro"),
                    ("X", "Xtreme"),
                    ("D", "Divine"),
                ],
                default="B",
                help_text="WARNING! To change the profile type correctly, please use the 'change_type_of_profile' method",
                max_length=1,
            ),
        ),
        migrations.DeleteModel(
            name="Diary",
        ),
    ]
