# Generated by Django 5.0.1 on 2024-04-09 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0024_alter_profile_size_of_pictures_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="visitors",
            field=models.ManyToManyField(
                blank=True, related_name="visited_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
