# Generated by Django 5.0.1 on 2024-04-09 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0025_profile_visitors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Guestbook",
        ),
    ]
