# Generated by Django 5.0.1 on 2024-04-10 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0026_delete_guestbook"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="description",
            new_name="presentation",
        ),
    ]
