# Generated by Django 5.0.1 on 2024-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Puls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_photo",
                    models.FloatField(
                        default=0, help_text="PLUS for accepted profile photo."
                    ),
                ),
                (
                    "about_me",
                    models.FloatField(
                        default=0, help_text="PLUS for fill the section 'about me' in."
                    ),
                ),
                (
                    "presentation",
                    models.FloatField(
                        default=0, help_text="PLUS for fill own presentation in."
                    ),
                ),
                (
                    "schools",
                    models.FloatField(default=0, help_text="PLUS for fill schools in."),
                ),
                (
                    "logins",
                    models.FloatField(
                        default=0, help_text="PLUS for log in to the server."
                    ),
                ),
                (
                    "guestbooks",
                    models.FloatField(
                        default=0, help_text="PLUS for entres to guestbooks."
                    ),
                ),
                (
                    "diaries",
                    models.FloatField(
                        default=0, help_text="PLUS for entres to diaries."
                    ),
                ),
                (
                    "surfing",
                    models.FloatField(
                        default=0, help_text="PLUS for surfint the Epuls."
                    ),
                ),
                (
                    "activity",
                    models.FloatField(
                        default=0, help_text="PLUS for other different activities."
                    ),
                ),
                (
                    "type",
                    models.FloatField(
                        default=0,
                        help_text="PLUS for type of account: Pro/Extrime/Divine. Once a month.",
                    ),
                ),
            ],
        ),
    ]
