# Generated by Django 5.0.1 on 2024-02-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puls", "0003_alter_puls_about_me_alter_puls_activity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SinglePuls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("quantity", models.FloatField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("profile_photo", "PROFILE PHOTO"),
                            ("about_me", "ABOUT ME"),
                            ("presentation", "PRESENTATION"),
                            ("schools", "SCHOOLS"),
                            ("logins", "LOGINS"),
                            ("guestbooks", "GUESTBOOKS"),
                            ("messages", "MESSAGES"),
                            ("diaries", "DIARIES"),
                            ("surfing", "SURFING"),
                            ("activity", "ACTIVITY"),
                            ("type", "TYPE"),
                        ],
                        max_length=25,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "puls",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulses",
                        to="puls.puls",
                    ),
                ),
            ],
        ),
    ]
