# Generated by Django 5.0.1 on 2024-01-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('politics', models.CharField(blank=True, max_length=50, null=True)),
                ('dish', models.CharField(blank=True, max_length=50, null=True)),
                ('film', models.CharField(blank=True, max_length=50, null=True)),
                ('song', models.CharField(blank=True, max_length=50, null=True)),
                ('idol', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.aboutuser'),
        ),
    ]
