# Generated by Django 5.0.1 on 2024-02-16 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("photo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="photo.profilepicture"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="receiver",
            field=models.ForeignKey(
                help_text="The user who had been visited.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="visitor",
            field=models.ForeignKey(
                help_text="The user who visited someone profile.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visitors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
