# Generated by Django 5.0.1 on 2024-01-29 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_visitor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guestbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry", models.TextField(help_text="Say hello!")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="The person who receive message.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_gb_entry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="The person who types something.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_gb_entry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
