# Generated by Django 5.0.1 on 2024-01-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_guestbook_options_diary"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="is_hide",
            field=models.BooleanField(default=False, verbose_name="hide"),
        ),
    ]
