# Generated by Django 5.0.1 on 2024-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="message",
        ),
        migrations.AddField(
            model_name="action",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[("own_profile", "OWN_PROFILE"), ("own_diary", "OWN_DIARY")],
                max_length=40,
                null=True,
            ),
        ),
    ]
