# Generated by Django 5.0.1 on 2024-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0002_remove_action_message_action_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="action",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("own_profile", "OWN_PROFILE"),
                    ("sb_profile", "SB_PROFILE"),
                    ("own_diary", "OWN_DIARY"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
