# Generated by Django 5.0.1 on 2024-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="puls",
            name="messages",
            field=models.IntegerField(default=0, help_text="PULS for amount messages."),
        ),
    ]
