# Generated by Django 5.0.1 on 2024-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puls", "0004_singlepuls"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("scaler", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("all", "ALL"),
                            ("logins", "LOGINS"),
                            ("guestbooks", "GUESTBOOKS"),
                            ("messages", "MESSAGES"),
                            ("diaries", "DIARIES"),
                            ("surfing", "SURFING"),
                            ("activity", "ACTIVITY"),
                            ("type", "TYPE"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
