# Generated by Django 5.0.1 on 2024-03-04 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("puls", "0005_bonus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bonus",
            options={"verbose_name_plural": "Bonuses"},
        ),
    ]
