# Generated by Django 5.0.1 on 2024-03-11 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puls", "0007_alter_singlepuls_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puls",
            name="schools",
            field=models.IntegerField(
                default=0,
                help_text="PLUS for fill schools in.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
    ]
