# Generated by Django 5.0.1 on 2024-03-11 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puls", "0008_alter_puls_schools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puls",
            name="about_me",
            field=models.IntegerField(
                default=0,
                help_text="PLUS for fill the section 'about me' in.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="puls",
            name="guestbooks",
            field=models.IntegerField(
                default=0, help_text="PLUS for entres to guestbooks."
            ),
        ),
        migrations.AlterField(
            model_name="puls",
            name="presentation",
            field=models.IntegerField(
                default=0,
                help_text="PLUS for fill own presentation in.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="puls",
            name="profile_photo",
            field=models.IntegerField(
                default=0,
                help_text="PLUS for accepted profile photo.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
    ]
