# Generated by Django 5.0.1 on 2024-04-18 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puls", "0009_alter_puls_about_me_alter_puls_guestbooks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puls",
            name="account_confirm",
            field=models.IntegerField(
                default=0,
                help_text="PLUS for fill schools in.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="singlepuls",
            name="type",
            field=models.CharField(
                choices=[
                    ("profile_photo", "PROFILE PHOTO"),
                    ("about_me", "ABOUT ME"),
                    ("presentation", "PRESENTATION"),
                    ("schools", "SCHOOLS"),
                    ("account_confirm", "ACCOUNT CONFIRM"),
                    ("logins", "LOGINS"),
                    ("guestbooks", "GUESTBOOKS"),
                    ("messages", "MESSAGES"),
                    ("diaries", "DIARIES"),
                    ("surfing", "SURFING"),
                    ("activity", "ACTIVITY"),
                    ("type", "TYPE"),
                    ("bonus", "BONUS"),
                ],
                max_length=25,
            ),
        ),
    ]
