# Generated by Django 5.0.1 on 2024-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("puls", "0011_alter_singlepuls_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlepuls",
            name="type",
            field=models.CharField(
                choices=[
                    ("profile_photo", "PROFILE PHOTO"),
                    ("about_me", "ABOUT ME"),
                    ("presentation", "PRESENTATION"),
                    ("schools", "SCHOOLS"),
                    ("account_confirm", "ACCOUNT CONFIRM"),
                    ("logins", "LOGINS"),
                    ("guestbooks", "GUESTBOOKS"),
                    ("messages", "MESSAGES"),
                    ("diaries", "DIARIES"),
                    ("surfing", "SURFING"),
                    ("comment_activity_picture", "COMMENT ACTIVITY"),
                    ("comment_activity_diary", "COMMENT ACTIVITY DIARY"),
                    ("activity", "ACTIVITY"),
                    ("type", "TYPE"),
                    ("bonus", "BONUS"),
                ],
                max_length=25,
            ),
        ),
    ]
