# Generated by Django 5.0.1 on 2024-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0003_profilepicturerequest_delete_profilepicture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilepicturerequest",
            old_name="date_accepted",
            new_name="examination_date",
        ),
        migrations.AlterField(
            model_name="profilepicturerequest",
            name="picture",
            field=models.ImageField(
                upload_to="profile_picture_request", verbose_name="profile picture"
            ),
        ),
    ]
