# Generated by Django 5.0.1 on 2024-02-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0005_profilepicturerequest_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="description",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
