# Generated by Django 5.0.1 on 2024-04-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0003_alter_action_options_alter_action_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("own_profile", "OWN_PROFILE"),
                    ("sb_profile", "SB_PROFILE"),
                    ("own_guestbook", "OWN_GUESTBOOK"),
                    ("sb_guestbook", "SB_GUESTBOOK"),
                    ("own_diary", "OWN_DIARY"),
                    ("sb_diary", "SB_DIARY"),
                    ("own_friends", "OWN_FRIENDS"),
                    ("sb_friends", "OWN_FRIENDS"),
                    ("own_gallery", "OWN_GALLERY"),
                    ("sb_gallery", "SB_GALLERY"),
                    ("own_puls", "OWN_PULS"),
                    ("sb_puls", "SB_PULS"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
