# Generated by Django 5.0.1 on 2024-03-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_remove_friendrequest_created_and_more"),
        ("clipboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clipboard",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="account.profile"
            ),
        ),
    ]
