# Generated by Django 5.0.1 on 2024-03-18 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clipboard", "0002_alter_clipboard_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clipboard",
            name="expiry",
        ),
        migrations.AlterField(
            model_name="clipboard",
            name="best_friends",
            field=models.ManyToManyField(
                blank=True,
                related_name="clipboard_best_friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clipboard",
            name="friends",
            field=models.ManyToManyField(
                blank=True,
                related_name="clipboard_friends",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
