# Generated by Django 5.0.1 on 2024-05-20 19:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_diarycomment"),
        ("like", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likephotocomment",
            unique_together={("comment", "user")},
        ),
    ]
