# Generated by Django 5.0.1 on 2024-02-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_profile_profile_picture"),
        ("photo", "0002_profilepicture_is_rejected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePictureRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="profile_picture_request")),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                ("date_accepted", models.DateTimeField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ProfilePicture",
        ),
    ]
