# Generated by Django 5.0.1 on 2024-03-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0007_alter_picture_gallery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepicturerequest",
            name="picture",
            field=models.ImageField(
                upload_to="profile_picture", verbose_name="profile picture"
            ),
        ),
    ]
