# Generated by Django 5.0.1 on 2024-03-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0023_profile_size_of_pictures"),
        ("photo", "0008_alter_profilepicturerequest_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to="account.profile",
            ),
        ),
    ]
