# Generated by Django 5.0.1 on 2024-04-09 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0009_alter_gallery_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="picture",
            options={"ordering": ["-date_created"]},
        ),
    ]
