# Generated by Django 5.0.1 on 2024-04-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0027_rename_description_profile_presentation"),
        ("photo", "0010_alter_picture_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="presentation_tag",
            field=models.CharField(
                default="test",
                help_text="Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="picture",
            unique_together={("title", "profile")},
        ),
    ]
