# Generated by Django 5.0.1 on 2024-04-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0011_picture_presentation_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="amt_comment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gallery",
            name="amt_like",
            field=models.IntegerField(default=0),
        ),
    ]
