# Generated by Django 5.0.1 on 2024-04-25 13:20

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0012_gallery_amt_comment_gallery_amt_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="popularity",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("amt_comment"), "+", models.F("amt_like")
                ),
                help_text="Number of comments and likes",
                output_field=models.IntegerField(),
            ),
        ),
    ]
