# Generated by Django 5.0.1 on 2024-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0013_gallery_popularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="sample",
            field=models.IntegerField(default=0),
        ),
    ]
