# Generated by Django 5.0.1 on 2024-04-26 18:41

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0014_gallery_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amt_comment", models.IntegerField(default=0)),
                ("amt_like", models.IntegerField(default=0)),
                (
                    "popularity",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("amt_comment"), "+", models.F("amt_like")
                        ),
                        help_text="Number of comments and likes",
                        output_field=models.IntegerField(),
                    ),
                ),
            ],
        ),
    ]
