# Generated by Django 5.0.1 on 2024-04-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0015_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="stats",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="photo.stats"
            ),
        ),
    ]
