# Generated by Django 5.0.1 on 2024-04-26 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0017_remove_gallery_sample"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="popularity",
        ),
    ]
