# Generated by Django 5.0.1 on 2024-04-26 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0018_remove_gallery_popularity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="amt_comment",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="amt_like",
        ),
    ]
