# Generated by Django 5.0.1 on 2024-05-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0019_remove_gallery_amt_comment_remove_gallery_amt_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="stats",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="photo.stats"
            ),
        ),
    ]
