# Generated by Django 5.0.1 on 2024-05-02 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0020_picture_stats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="stats",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="stats",
        ),
        migrations.DeleteModel(
            name="Stats",
        ),
    ]
