# Generated by Django 5.0.1 on 2024-05-02 17:52

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0021_remove_picture_stats_remove_gallery_stats_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amt_comments", models.IntegerField(default=0)),
                ("amt_likes", models.IntegerField(default=0)),
                ("total_views", models.IntegerField(default=0)),
                (
                    "popularity",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("amt_comments"), "+", models.F("amt_likes")
                            ),
                            "+",
                            models.F("total_views"),
                        ),
                        help_text="Calculated as the sum of comments, likes, and views.",
                        output_field=models.IntegerField(),
                    ),
                ),
                (
                    "gallery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="photo.gallery",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stats",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PictureStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amt_comments", models.IntegerField(default=0)),
                ("amt_likes", models.IntegerField(default=0)),
                ("total_views", models.IntegerField(default=0)),
                (
                    "popularity",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("amt_comments"), "+", models.F("amt_likes")
                            ),
                            "+",
                            models.F("total_views"),
                        ),
                        help_text="Calculated as the sum of comments, likes, and views.",
                        output_field=models.IntegerField(),
                    ),
                ),
                (
                    "picture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="photo.picture",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stats",
                "abstract": False,
            },
        ),
    ]
